### ISSUE TITLE
Single condition is mandated in group

### ISSUE THREAD

**Issue by ubreddy** [niklr/angular-query-builder#2]
QB could have a group of groups without conditions.
1. So, ideally the add New condition button should be at group level.
2. Group could start with zero conditions and groups.
3. canRemove condition should be true even for one condition in the group.
4. group could contain either of condition or sub-group

**Comment by niklr** [comment]
Can you give me a query example with a group having no condition? Or why do you need the group to start with zero conditions?

**Comment by ubreddy** [comment]
( a and b) or( c and d)
Uday

**Comment by niklr** [comment]
Solved with commit https://github.com/niklr/angular-query-builder/commit/aa41eec96844ed395627e8cf0da5c5fb0704c162
