### ISSUE TITLE
UNCAUGHT ERROR

### ISSUE THREAD

**Issue by dineplan** [niklr/angular-query-builder#3]
Hello 

I am trying to use this plugin into my application. But it gives the " angular.js:38Uncaught Error: [$injector:modulerr]"

I have already included in angular.module as well.

Is there else i have to do ?

**Comment by niklr** [comment]
I just updated the documentation and hope this helps. A good starting point is looking at how the demo app is wired up: http://niklr.github.io/angular-query-builder
